"""Tests for Phase 14 modular multi-stage reasoning."""

from __future__ import annotations

import json
from typing import Any

from finance_agent.reasoning.reasoning_pipeline import (
    build_financial_performance_prompt,
    build_strategic_synthesis_prompt,
    create_modular_strategic_analysis,
    normalize_reasoning_stage_payload,
    reasoning_stage_json_schema,
    validate_reasoning_stage_response,
)
from finance_agent.analysis.strategic_analysis import build_evidence_ledger
from finance_agent.reporting.report_engine import ReportInputBundle, build_report_model
from finance_agent.reporting.renderers import render_report_html
from finance_agent.reporting.report_quality import validate_report_model_quality
from finance_agent.reasoning.fact_registry import FactRegistry
from finance_agent.reasoning.reasoning_models import ReasoningStageResult
from finance_agent.reasoning.reasoning_state import ReasoningState


class FakeReasoningClient:
    """Small mocked Ollama client for deterministic reasoning tests."""

    def __init__(self, responses: tuple[dict[str, Any], ...]) -> None:
        """Store queued JSON responses.

        Inputs: response payloads for Stage 1, Stage 2, and Stage 3.
        Outputs: initialized fake client.
        Assumptions: tests do not require a live Ollama server.
        """

        self.responses = [json.dumps(response, ensure_ascii=False) for response in responses]
        self.response_format: str | dict[str, Any] = "json"
        self.prompts: list[str] = []

    def is_available(self) -> bool:
        """Return mocked availability.

        Inputs: none.
        Outputs: True.
        Assumptions: availability is controlled by tests through responses.
        """

        return True

    def generate_with_metadata(self, prompt: str) -> dict[str, Any]:
        """Return the next queued response plus tiny telemetry.

        Inputs: prompt generated by the reasoning stage.
        Outputs: Ollama-like response envelope.
        Assumptions: one call is made per modular stage.
        """

        self.prompts.append(prompt)
        response = self.responses.pop(0)
        return {
            "response": response,
            "telemetry": {
                "prompt_characters": len(prompt),
                "generation_time_seconds": 0.001,
            },
        }


def _finance_summary() -> dict[str, Any]:
    """Return a compact processed finance summary fixture.

    Inputs: none.
    Outputs: finance summary dictionary.
    Assumptions: values are deterministic and processed, not raw workbook rows.
    """

    return {
        "period_slug": "2026_12",
        "report_period": "2026_12",
        "finance_summary": {
            "total_revenue": 1000,
            "total_expenses": 900,
            "net_operating_result": 100,
            "payroll_total": 400,
            "payroll_percentage_of_revenue": 0.4,
            "budget_vs_actual": {"expense_variance": 25},
            "student_payments": {"collection_rate": 0.95},
            "cash_flow": {"net_cash_flow": 50, "ending_cash": 500},
        },
        "department_summary": [{"department": "Health Sciences", "variance": 25}],
    }


def _anomaly_report() -> dict[str, Any]:
    """Return a compact processed anomaly report fixture.

    Inputs: none.
    Outputs: anomaly report dictionary.
    Assumptions: anomaly IDs are stable evidence anchors.
    """

    return {
        "period_slug": "2026_12",
        "report_period": "2026_12",
        "total_anomalies": 1,
        "anomalies": [
            {
                "anomaly_id": "ANOM-1",
                "title": "Riesgo de gasto",
                "severity": "high",
                "metric": "expense_variance",
                "observed_value": 25,
                "period": "2026_12",
                "department": "Health Sciences",
            }
        ],
    }


def _evidence_package() -> dict[str, Any]:
    """Return a compact evidence package fixture.

    Inputs: none.
    Outputs: evidence package dictionary.
    Assumptions: retrieval has already run and no LLM analysis is included.
    """

    return {
        "period_slug": "2026_12",
        "summary": {"tasks_executed": 1, "successful_retrievals": 1},
        "evidence_packages": [
            {
                "task_id": "TASK-1",
                "investigation_question": "Revisar gasto",
                "evidence_summary": "Evidencia departamental disponible.",
                "retrieved_evidence": {"retrieval_name": "department_history", "data": {}},
            }
        ],
    }


def _risk_summary() -> dict[str, Any]:
    """Return a compact risk summary fixture.

    Inputs: none.
    Outputs: risk summary dictionary.
    Assumptions: risk summary is processed JSON.
    """

    return {"overall_risk_level": "high", "high_count": 1}


def _stage_1() -> dict[str, Any]:
    """Return valid Stage 1 mocked output.

    Inputs: none.
    Outputs: Stage 1 JSON payload.
    Assumptions: all evidence IDs exist in the ledger.
    """

    return {
        "claims": [
            {
                "text": "El resultado operativo es positivo con $100.",
                "confidence": 0.84,
                "claim_type": "fact",
            }
        ],
        "risks": [
            {
                "text": "El gasto departamental de Health Sciences requiere seguimiento ejecutivo.",
                "confidence": 0.8,
            }
        ],
        "opportunities": [
            {
                "text": "La cobranza ofrece una base favorable para sostener liquidez con 95.0%.",
                "confidence": 0.78,
            }
        ],
        "open_questions": [],
    }


def _stage_2() -> dict[str, Any]:
    """Return valid Stage 2 mocked output.

    Inputs: none.
    Outputs: Stage 2 JSON payload.
    Assumptions: historical claims cite known current evidence in this fixture.
    """

    return {
        "claims": [
            {
                "text": "La evaluación histórica debe centrarse en el seguimiento del gasto de Health Sciences.",
                "confidence": 0.8,
                "claim_type": "interpretation",
            }
        ],
        "opportunities": [
            {
                "text": "La tendencia validada mantiene el foco en disciplina operativa con 40.0%.",
                "confidence": 0.76,
            }
        ],
        "risks": [
            {
                "text": "El riesgo persistente está asociado al control departamental de Health Sciences.",
                "confidence": 0.77,
            }
        ],
        "open_questions": [],
    }


def _stage_3() -> dict[str, Any]:
    """Return valid strategic synthesis mocked output.

    Inputs: none.
    Outputs: Step-9-compatible strategic-analysis payload.
    Assumptions: every narrative field cites a supporting evidence ID.
    """

    return {
        "executive_summary": "La posición financiera requiere gestión disciplinada con $100.",
        "key_findings": ["El resultado operativo mantiene una señal favorable con $100."],
        "root_causes": ["La hipótesis principal es presión operativa asociada a Health Sciences."],
        "financial_health_analysis": "La salud financiera muestra margen operativo positivo con $100.",
        "kpi_analysis": "Los KPI priorizan resultado operativo sustentado en $100.",
        "department_analysis": "Health Sciences requiere seguimiento por varianza departamental de $25.",
        "anomaly_analysis": "La anomalía de gasto concentra el riesgo operativo.",
        "recommendation_follow_up_analysis": "El seguimiento debe confirmar ejecución de controles motivados por $25.",
        "longitudinal_risk_analysis": "El riesgo longitudinal debe monitorearse con evidencia de gasto.",
        "strategic_recommendations": [
            {
                "priority": "high",
                "action": "Revisar controles de gasto departamental en Health Sciences.",
                "rationale": "La evidencia validada muestra una varianza de $25 que requiere atención.",
                "supporting_evidence": "Varianza departamental y anomalía de gasto.",
                "expected_impact": "Mejorar la disciplina presupuestaria asociada a Health Sciences sin modificar los datos financieros.",
                "confidence": 0.82,
            }
        ],
        "strategic_priorities": ["Disciplina operativa y seguimiento departamental en Health Sciences."],
        "missing_information": ["La información faltante debe revisarse contra evidencia departamental disponible."],
        "historical_summary": "La lectura histórica se limita a evidencia validada disponible.",
        "historical_trend_analysis": "La tendencia debe monitorearse sin inferir valores no suministrados.",
        "confidence": 0.82,
        "reasoning_summary": "La síntesis usa únicamente evidencia validada por etapas.",
    }


def _stage_3_with_unsupported_recommendation_budget() -> dict[str, Any]:
    """Return Stage 3 output with repairable unsupported recommendation specifics."""

    payload = _stage_3()
    payload["strategic_recommendations"][0]["action"] = (
        "Invertir $50,000 para corregir el gasto de Health Sciences."
    )
    payload["strategic_recommendations"][0]["expected_impact"] = (
        "Reducir el gasto en 90.0% por esta acciÃ³n."
    )
    return payload


def _stage_3_with_unsupported_causal_statement() -> dict[str, Any]:
    """Return Stage 3 output with repairable causal certainty."""

    payload = _stage_3()
    payload["strategic_recommendations"][0]["rationale"] = (
        "La desviaciÃ³n fue causada por aprobaciones internas sin evidencia validada."
    )
    return payload


def _ledger() -> dict[str, Any]:
    """Build the shared evidence ledger fixture.

    Inputs: none.
    Outputs: evidence ledger dictionary.
    Assumptions: helper mirrors production ledger generation.
    """

    return build_evidence_ledger(
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        evidence_package=_evidence_package(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )


def _placeholder(evidence_id: str, metric_name: str | None = None) -> str:
    """Return a deterministic placeholder for one fixture fact.

    Inputs: evidence ID and optional metric name.
    Outputs: placeholder token such as ``{{FACT_020}}``.
    Assumptions: fact registry ordering is stable for the fixture ledger.
    """

    registry = FactRegistry.from_evidence_ledger(_ledger())
    for fact in registry.facts:
        if evidence_id in fact.evidence_ids and (metric_name is None or fact.metric_name == metric_name):
            return fact.placeholder
    raise AssertionError(f"Missing placeholder for {evidence_id}/{metric_name}")


def test_reasoning_state_propagates_validated_outputs() -> None:
    """Verify ReasoningState stores accepted stage outputs by responsibility."""

    state = ReasoningState(period_slug="2026_12", evidence_ledger=_ledger())
    validation = validate_reasoning_stage_response(
        json.dumps(_stage_1(), ensure_ascii=False),
        stage_id="financial_performance",
        evidence_ledger=_ledger(),
    )
    assert validation.is_valid
    state.add_stage_result(
        ReasoningStageResult(
            stage_id="financial_performance",
            stage_name="Financial",
            accepted=True,
            payload=validation.payload or {},
            validation_errors=(),
            telemetry={},
        )
    )

    assert state.validated_claims[0]["stage_id"] == "financial_performance"
    assert state.risks[0]["text"]


def test_context_propagation_avoids_full_ledger_in_strategic_prompt() -> None:
    """Verify Stage 3 receives validated reasoning state, not the full ledger."""

    state = ReasoningState(period_slug="2026_12", evidence_ledger=_ledger())
    state.add_stage_result(
        ReasoningStageResult("financial_performance", "Financial", True, _stage_1(), (), {})
    )
    prompt = build_strategic_synthesis_prompt(
        state=state,
        finance_summary=_finance_summary(),
        period_slug="2026_12",
    )

    assert "validated_reasoning_state" in prompt
    assert "evidence_ledger" not in prompt
    assert "resolved_evidence_ids" not in prompt
    assert "validated_claims" in prompt


def test_duplicate_context_prevention_in_financial_prompt() -> None:
    """Verify Stage 1 prompt does not duplicate evidence package row payloads."""

    prompt = build_financial_performance_prompt(
        evidence_ledger=_ledger(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        period_slug="2026_12",
    )

    assert "payroll_breakdown" not in prompt
    assert "finance.metric.net_operating_result" not in prompt
    assert '"value":"$100"' in prompt


def test_llm_facing_schema_uses_text_not_supporting_facts_or_evidence_ids() -> None:
    """Verify modular stage schemas ask for reasoning text only."""

    schema_text = json.dumps(reasoning_stage_json_schema("financial_performance"), ensure_ascii=False)

    assert '"text"' in schema_text
    assert "supporting_facts" not in schema_text
    assert "evidence_ids" not in schema_text


def test_model_supplied_evidence_ids_are_rejected() -> None:
    """Verify legacy evidence IDs in model output are not accepted."""

    payload = _stage_1()
    payload["claims"][0]["evidence_ids"] = ["finance.metric.net_operating_result"]
    validation = validate_reasoning_stage_response(
        json.dumps(payload, ensure_ascii=False),
        stage_id="financial_performance",
        evidence_ledger=_ledger(),
    )

    assert not validation.is_valid
    assert validation.errors[0].startswith("schema:")


def test_stage_rejects_unsupported_period_claim() -> None:
    """Verify Stage 1 rejects unsupported deterministic period claims."""

    ledger = _ledger()
    ledger["facts"].append(
        {
            "evidence_id": "history.metric.payroll_ratio",
            "metric": "payroll_ratio",
            "display_value": "44.0%",
            "raw_value": 0.44,
            "unit": "ratio",
            "period": "2026_11",
            "entity": "",
            "source_reference": "data/memory/recovery_2026_memory.db",
        }
    )
    payload = _stage_1()
    payload["claims"][0]["text"] = "El ratio histórico de 2027_01 fue 44.0%."
    validation = validate_reasoning_stage_response(
        json.dumps(payload, ensure_ascii=False),
        stage_id="financial_performance",
        evidence_ledger=ledger,
    )

    assert not validation.is_valid
    assert any("unsupported period" in error or "unsupported number" in error for error in validation.errors)


def test_independent_stage_validation_rejects_unsupported_number() -> None:
    """Verify Stage 1 validation rejects invented values before later stages."""

    payload = _stage_1()
    payload["claims"][0]["text"] = "El resultado operativo inventado es 9999."
    validation = validate_reasoning_stage_response(
        json.dumps(payload, ensure_ascii=False),
        stage_id="financial_performance",
        evidence_ledger=_ledger(),
    )

    assert not validation.is_valid
    assert any("unsupported number" in error or "numeric literal" in error for error in validation.errors)


def test_alias_keys_normalize_correctly() -> None:
    """Verify safe synonymous keys normalize into the minimal schema."""

    payload = {
        "identified_risks": [{"text": "El riesgo requiere control.", "confidence_level": 0.7}],
        "identified_opportunities": [{"text": "La cobranza permite sostener liquidez.", "confidence_level": 0.7}],
        "financial_claims": [{"text": "El resultado operativo es positivo con $100.", "confidence_level": 0.8, "claim_type": "fact"}],
        "questions": [],
    }

    normalized, changes = normalize_reasoning_stage_payload(payload)

    assert set(normalized) == {"claims", "risks", "opportunities", "open_questions"}
    assert normalized["claims"][0]["confidence"] == 0.8
    assert any(change["from"] == "identified_risks" for change in changes)


def test_wrapper_object_unwraps_without_inventing_claims() -> None:
    """Verify adapter unwraps one obvious wrapper and preserves item content."""

    wrapped = {"financial_reasoning": {"claims": [], "risks": [], "opportunities": [], "open_questions": []}}
    normalized, changes = normalize_reasoning_stage_payload(wrapped)

    assert normalized == {"claims": [], "risks": [], "opportunities": [], "open_questions": []}
    assert changes == [{"kind": "unwrap", "from": "financial_reasoning", "to": "root"}]


def test_unknown_top_level_keys_rejected_after_normalization() -> None:
    """Verify unknown model keys remain rejected after safe alias normalization."""

    payload = {**_stage_1(), "unexpected": []}
    validation = validate_reasoning_stage_response(
        json.dumps(payload, ensure_ascii=False),
        stage_id="financial_performance",
        evidence_ledger=_ledger(),
    )

    assert not validation.is_valid
    assert validation.errors[0].startswith("schema:")


def test_stage_1_semantic_alias_output_becomes_valid() -> None:
    """Verify observed Ollama-style aliases are accepted after normalization."""

    payload = {
        "financial_claims": [
            {
                "text": "El resultado operativo es positivo con $100.",
                "confidence_level": 0.8,
                "claim_type": "fact",
            }
        ],
        "identified_risks": [
            {
                "text": "El gasto departamental requiere seguimiento ejecutivo.",
                "confidence_level": 0.7,
            }
        ],
        "identified_opportunities": [],
        "questions": [],
    }
    validation = validate_reasoning_stage_response(
        json.dumps(payload, ensure_ascii=False),
        stage_id="financial_performance",
        evidence_ledger=_ledger(),
    )

    assert validation.is_valid
    assert validation.payload is not None
    assert validation.payload["_schema_normalizations"]


def test_schema_only_retry_preserves_original_fact_content() -> None:
    """Verify schema retry can restructure aliases without adding evidence."""

    aliased = {
        "financial_claims": [
            {
                "text": "El resultado operativo es positivo con $100.",
                "confidence_level": 0.8,
                "claim_type": "fact",
            }
        ],
        "identified_risks": [],
        "identified_opportunities": [],
        "questions": [],
        "confidence_level": 0.8,
    }
    repaired = {
        "claims": aliased["financial_claims"],
        "risks": [],
        "opportunities": [],
        "open_questions": [],
    }
    client = FakeReasoningClient((aliased, repaired, _stage_2(), _stage_3()))
    result = create_modular_strategic_analysis(
        client=client,
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )

    assert result.accepted
    first_stage = result.analysis_document["reasoning_state"]["stage_results"][0]
    assert first_stage["telemetry"]["schema_retry_attempted"] is True
    assert first_stage["payload"]["claims"][0]["text"] == "El resultado operativo es positivo con $100."


def test_stage_validation_rejection_is_telemetry_category() -> None:
    """Verify schema-invalid stage output is categorized as validation rejection."""

    client = FakeReasoningClient(({"bad": "shape"}, {"bad": "shape"}))
    result = create_modular_strategic_analysis(
        client=client,
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )

    first_stage = result.analysis_document["reasoning_state"]["stage_results"][0]
    assert first_stage["telemetry"]["error_category"] == "validation_rejection"


def test_modular_pipeline_runs_three_stages_with_mocked_ollama() -> None:
    """Verify the modular pipeline returns accepted Step-9-compatible output."""

    client = FakeReasoningClient((_stage_1(), _stage_2(), _stage_3()))
    result = create_modular_strategic_analysis(
        client=client,
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )

    assert result.accepted
    assert len(client.prompts) == 3
    assert result.analysis_document["analysis_source"] == "ollama_modular_reasoning"
    assert result.analysis_document["reasoning_state"]["reasoning_outputs"]["strategic_synthesis"]
    report_ready_analysis = {
        key: value
        for key, value in result.analysis_document["analysis"].items()
        if not str(key).startswith("_")
    }
    analysis_text = json.dumps(report_ready_analysis, ensure_ascii=False)
    assert "{{FACT_" not in analysis_text
    assert "finance.metric.net_operating_result" not in result.analysis_document["analysis"]["executive_summary"]


def test_unsupported_recommendation_budget_is_sanitized_not_fatal() -> None:
    """Verify unsupported recommendation amounts/percentages are sanitized."""

    result = create_modular_strategic_analysis(
        client=FakeReasoningClient((_stage_1(), _stage_2(), _stage_3_with_unsupported_recommendation_budget())),
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )

    recommendation = result.analysis_document["analysis"]["strategic_recommendations"][0]
    combined = json.dumps(recommendation, ensure_ascii=False)

    assert result.accepted is True
    assert result.analysis_document["validation_status"] == "sanitized"
    assert "$50,000" not in combined
    assert "90.0%" not in combined
    assert "Definir montos" in combined
    assert result.analysis_document["strategic_recovery"]["sanitized_fields"]


def test_unsupported_causal_recommendation_is_softened_not_fatal() -> None:
    """Verify unsupported causal certainty is converted into a hypothesis."""

    result = create_modular_strategic_analysis(
        client=FakeReasoningClient((_stage_1(), _stage_2(), _stage_3_with_unsupported_causal_statement())),
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )

    recommendation = result.analysis_document["analysis"]["strategic_recommendations"][0]

    assert result.accepted is True
    assert result.analysis_document["validation_status"] == "sanitized"
    assert "hipótesis" in recommendation["rationale"].casefold()
    assert "requiere validación" in recommendation["rationale"].casefold()


def test_failed_strategy_still_builds_deterministic_report_model() -> None:
    """Verify deterministic report content remains renderable when strategy fails."""

    result = create_modular_strategic_analysis(
        client=FakeReasoningClient(({"bad": "shape"}, {"bad": "shape"})),
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )
    model = build_report_model(
        ReportInputBundle(
            period_slug="2026_12",
            finance_summary=_finance_summary(),
            kpi_summary=(),
            anomaly_report=_anomaly_report(),
            evidence_package=_evidence_package(),
            strategic_analysis=result.analysis_document,
            source_files=(
                "outputs/calculations/finance_summary_2026_12.json",
                "outputs/calculations/kpi_summary_2026_12.json",
                "outputs/anomalies/anomaly_report_2026_12.json",
                "outputs/evidence/evidence_package_2026_12.json",
                "outputs/analysis/strategic_analysis_2026_12.json",
            ),
        )
    )
    model_dict = model.to_dict()
    quality = validate_report_model_quality(model_dict)
    html = render_report_html(model_dict)

    assert result.accepted is True
    assert result.analysis_document["analysis_source"] == "degraded_deterministic"
    assert result.analysis_document["strategic_recovery"]["degraded_mode"] is True
    assert result.analysis_document["strategic_recovery"]["source_label"] == "Modo degradado: análisis determinístico"
    assert quality.is_valid is True
    assert "Modo degradado" in html
    assert "No hay recomendaciones estratégicas validadas" not in html


def test_stage_timeout_checkpoint_metadata_is_preserved() -> None:
    """Verify a late returned response remains usable with timeout telemetry."""

    class SlowClient(FakeReasoningClient):
        """Fake client whose call exceeds the configured stage timeout."""

        def generate_with_metadata(self, prompt: str) -> dict[str, Any]:
            """Return valid JSON but with no need for a real sleep."""

            result = super().generate_with_metadata(prompt)
            return result

    result = create_modular_strategic_analysis(
        client=SlowClient((_stage_1(), _stage_2(), _stage_3())),
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
        stage_timeout_seconds=0.0,
    )

    assert result.accepted
    first_stage = result.analysis_document["reasoning_state"]["stage_results"][0]
    assert first_stage["accepted"] is True
    assert first_stage["telemetry"]["stage_timeout_budget_exceeded"] is True
    assert first_stage["telemetry"]["timeout_error_category"] == "stage_timeout"


def test_report_generation_reads_validated_reasoning_state() -> None:
    """Verify report model can render from ReasoningState strategic synthesis."""

    result = create_modular_strategic_analysis(
        client=FakeReasoningClient((_stage_1(), _stage_2(), _stage_3())),
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )
    document = dict(result.analysis_document)
    document["analysis"] = {}
    model = build_report_model(
        ReportInputBundle(
            period_slug="2026_12",
            finance_summary=_finance_summary(),
            kpi_summary=(),
            anomaly_report=_anomaly_report(),
            evidence_package=_evidence_package(),
            strategic_analysis=document,
            source_files=(
                "outputs/calculations/finance_summary_2026_12.json",
                "outputs/calculations/kpi_summary_2026_12.json",
                "outputs/anomalies/anomaly_report_2026_12.json",
                "outputs/evidence/evidence_package_2026_12.json",
                "outputs/analysis/strategic_analysis_2026_12.json",
            ),
        )
    ).to_dict()

    executive = next(section for section in model["sections"] if section["section_id"] == "executive_summary")
    assert "posición financiera" in executive["content"]["summary"]
