"""Tests for Phase 14 modular multi-stage reasoning."""

from __future__ import annotations

import json
from typing import Any

from finance_agent.reasoning.reasoning_pipeline import (
    build_financial_performance_prompt,
    build_strategic_synthesis_prompt,
    create_modular_strategic_analysis,
    normalize_reasoning_stage_payload,
    validate_reasoning_stage_response,
)
from finance_agent.analysis.strategic_analysis import build_evidence_ledger
from finance_agent.reporting.report_engine import ReportInputBundle, build_report_model
from finance_agent.reasoning.fact_registry import FactRegistry
from finance_agent.reasoning.reasoning_models import ReasoningStageResult
from finance_agent.reasoning.reasoning_state import ReasoningState


class FakeReasoningClient:
    """Small mocked Ollama client for deterministic reasoning tests."""

    def __init__(self, responses: tuple[dict[str, Any], ...]) -> None:
        """Store queued JSON responses.

        Inputs: response payloads for Stage 1, Stage 2, and Stage 3.
        Outputs: initialized fake client.
        Assumptions: tests do not require a live Ollama server.
        """

        self.responses = [json.dumps(response, ensure_ascii=False) for response in responses]
        self.response_format: str | dict[str, Any] = "json"
        self.prompts: list[str] = []

    def is_available(self) -> bool:
        """Return mocked availability.

        Inputs: none.
        Outputs: True.
        Assumptions: availability is controlled by tests through responses.
        """

        return True

    def generate_with_metadata(self, prompt: str) -> dict[str, Any]:
        """Return the next queued response plus tiny telemetry.

        Inputs: prompt generated by the reasoning stage.
        Outputs: Ollama-like response envelope.
        Assumptions: one call is made per modular stage.
        """

        self.prompts.append(prompt)
        response = self.responses.pop(0)
        return {
            "response": response,
            "telemetry": {
                "prompt_characters": len(prompt),
                "generation_time_seconds": 0.001,
            },
        }


def _finance_summary() -> dict[str, Any]:
    """Return a compact processed finance summary fixture.

    Inputs: none.
    Outputs: finance summary dictionary.
    Assumptions: values are deterministic and processed, not raw workbook rows.
    """

    return {
        "period_slug": "2026_12",
        "report_period": "2026_12",
        "finance_summary": {
            "total_revenue": 1000,
            "total_expenses": 900,
            "net_operating_result": 100,
            "payroll_total": 400,
            "payroll_percentage_of_revenue": 0.4,
            "budget_vs_actual": {"expense_variance": 25},
            "student_payments": {"collection_rate": 0.95},
            "cash_flow": {"net_cash_flow": 50, "ending_cash": 500},
        },
        "department_summary": [{"department": "Health Sciences", "variance": 25}],
    }


def _anomaly_report() -> dict[str, Any]:
    """Return a compact processed anomaly report fixture.

    Inputs: none.
    Outputs: anomaly report dictionary.
    Assumptions: anomaly IDs are stable evidence anchors.
    """

    return {
        "period_slug": "2026_12",
        "report_period": "2026_12",
        "total_anomalies": 1,
        "anomalies": [
            {
                "anomaly_id": "ANOM-1",
                "title": "Riesgo de gasto",
                "severity": "high",
                "metric": "expense_variance",
                "observed_value": 25,
                "period": "2026_12",
                "department": "Health Sciences",
            }
        ],
    }


def _evidence_package() -> dict[str, Any]:
    """Return a compact evidence package fixture.

    Inputs: none.
    Outputs: evidence package dictionary.
    Assumptions: retrieval has already run and no LLM analysis is included.
    """

    return {
        "period_slug": "2026_12",
        "summary": {"tasks_executed": 1, "successful_retrievals": 1},
        "evidence_packages": [
            {
                "task_id": "TASK-1",
                "investigation_question": "Revisar gasto",
                "evidence_summary": "Evidencia departamental disponible.",
                "retrieved_evidence": {"retrieval_name": "department_history", "data": {}},
            }
        ],
    }


def _risk_summary() -> dict[str, Any]:
    """Return a compact risk summary fixture.

    Inputs: none.
    Outputs: risk summary dictionary.
    Assumptions: risk summary is processed JSON.
    """

    return {"overall_risk_level": "high", "high_count": 1}


def _stage_1() -> dict[str, Any]:
    """Return valid Stage 1 mocked output.

    Inputs: none.
    Outputs: Stage 1 JSON payload.
    Assumptions: all evidence IDs exist in the ledger.
    """

    return {
        "claims": [
            {
                "text": "El resultado operativo es positivo según la evidencia actual.",
                "evidence_ids": ["finance.metric.net_operating_result"],
                "confidence": 0.84,
                "claim_type": "fact",
            }
        ],
        "risks": [
            {
                "text": "El gasto departamental requiere seguimiento ejecutivo.",
                "evidence_ids": ["anomaly.anom_1"],
                "confidence": 0.8,
            }
        ],
        "opportunities": [
            {
                "text": "La cobranza ofrece una base favorable para sostener liquidez.",
                "evidence_ids": ["finance.metric.collection_rate"],
                "confidence": 0.78,
            }
        ],
        "open_questions": [],
    }


def _stage_2() -> dict[str, Any]:
    """Return valid Stage 2 mocked output.

    Inputs: none.
    Outputs: Stage 2 JSON payload.
    Assumptions: historical claims cite known current evidence in this fixture.
    """

    return {
        "claims": [
            {
                "text": "La evaluación histórica debe centrarse en el seguimiento del gasto.",
                "evidence_ids": ["anomaly.anom_1"],
                "confidence": 0.8,
                "claim_type": "interpretation",
            }
        ],
        "opportunities": [
            {
                "text": "La tendencia validada mantiene el foco en disciplina operativa.",
                "evidence_ids": ["finance.metric.payroll_percentage_of_revenue"],
                "confidence": 0.76,
            }
        ],
        "risks": [
            {
                "text": "El riesgo persistente está asociado al control departamental.",
                "evidence_ids": ["anomaly.anom_1"],
                "confidence": 0.77,
            }
        ],
        "open_questions": [],
    }


def _stage_3() -> dict[str, Any]:
    """Return valid strategic synthesis mocked output.

    Inputs: none.
    Outputs: Step-9-compatible strategic-analysis payload.
    Assumptions: every narrative field cites a supporting evidence ID.
    """

    evidence = ["finance.metric.net_operating_result"]
    net_result = _placeholder("finance.metric.net_operating_result", "net_operating_result")
    department = _placeholder("finance.department.health_sciences.variance", "entity")
    variance = _placeholder("finance.department.health_sciences.variance", "variance")
    anomaly_title = _placeholder("anomaly.anom_1", "expense_variance")
    return {
        "executive_summary": {"text": f"La posición financiera requiere gestión disciplinada con {net_result}.", "evidence_ids": evidence},
        "key_findings": [f"El resultado operativo mantiene una señal favorable con {net_result}."],
        "root_causes": [f"La hipótesis principal es presión operativa asociada a {department}."],
        "financial_health_analysis": {"text": f"La salud financiera muestra margen operativo positivo con {net_result}.", "evidence_ids": evidence},
        "kpi_analysis": {"text": "Los KPI priorizan resultado operativo, cobranza y liquidez.", "evidence_ids": evidence},
        "department_analysis": {"text": f"{department} requiere seguimiento por varianza departamental de {variance}.", "evidence_ids": ["finance.department.health_sciences.variance"]},
        "anomaly_analysis": {"text": f"La anomalía {anomaly_title} concentra el riesgo operativo.", "evidence_ids": ["anomaly.anom_1"]},
        "recommendation_follow_up_analysis": {"text": "El seguimiento debe confirmar ejecución de controles.", "evidence_ids": evidence},
        "longitudinal_risk_analysis": {"text": "El riesgo longitudinal debe monitorearse con evidencia mensual.", "evidence_ids": evidence},
        "strategic_recommendations": [
            {
                "priority": "high",
                "action": f"Revisar controles de gasto departamental en {department}.",
                "rationale": f"La evidencia validada muestra una varianza de {variance} que requiere atención.",
                "supporting_evidence": "finance.metric.net_operating_result",
                "expected_impact": f"Mejorar la disciplina presupuestaria asociada a {department} sin modificar los datos financieros.",
                "evidence_ids": [
                    "finance.metric.net_operating_result",
                    "finance.department.health_sciences.variance",
                    "anomaly.anom_1",
                ],
                "confidence": 0.82,
            }
        ],
        "strategic_priorities": ["Disciplina operativa y seguimiento departamental."],
        "missing_information": [],
        "historical_summary": {"text": "La lectura histórica se limita a evidencia validada disponible.", "evidence_ids": evidence},
        "historical_trend_analysis": {"text": "La tendencia debe monitorearse sin inferir valores no suministrados.", "evidence_ids": evidence},
        "narrative_evidence": {
            "executive_summary": evidence,
            "key_findings": evidence,
            "root_causes": evidence,
            "financial_health_analysis": evidence,
            "kpi_analysis": evidence,
            "department_analysis": ["finance.department.health_sciences.variance"],
            "anomaly_analysis": ["anomaly.anom_1"],
            "recommendation_follow_up_analysis": evidence,
            "longitudinal_risk_analysis": evidence,
            "strategic_priorities": evidence,
            "missing_information": ["evidence.task_1.summary"],
            "historical_summary": evidence,
            "historical_trend_analysis": evidence,
            "reasoning_summary": evidence,
        },
        "confidence": 0.82,
        "reasoning_summary": {"text": "La síntesis usa únicamente evidencia validada por etapas.", "evidence_ids": evidence},
    }


def _ledger() -> dict[str, Any]:
    """Build the shared evidence ledger fixture.

    Inputs: none.
    Outputs: evidence ledger dictionary.
    Assumptions: helper mirrors production ledger generation.
    """

    return build_evidence_ledger(
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        evidence_package=_evidence_package(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )


def _placeholder(evidence_id: str, metric_name: str | None = None) -> str:
    """Return a deterministic placeholder for one fixture fact.

    Inputs: evidence ID and optional metric name.
    Outputs: placeholder token such as ``{{FACT_020}}``.
    Assumptions: fact registry ordering is stable for the fixture ledger.
    """

    registry = FactRegistry.from_evidence_ledger(_ledger())
    for fact in registry.facts:
        if evidence_id in fact.evidence_ids and (metric_name is None or fact.metric_name == metric_name):
            return fact.placeholder
    raise AssertionError(f"Missing placeholder for {evidence_id}/{metric_name}")


def test_reasoning_state_propagates_validated_outputs() -> None:
    """Verify ReasoningState stores accepted stage outputs by responsibility."""

    state = ReasoningState(period_slug="2026_12", evidence_ledger=_ledger())
    state.add_stage_result(
        ReasoningStageResult(
            stage_id="financial_performance",
            stage_name="Financial",
            accepted=True,
            payload=_stage_1(),
            validation_errors=(),
            telemetry={},
        )
    )

    assert state.validated_claims[0]["stage_id"] == "financial_performance"
    assert state.risks[0]["evidence_ids"] == ["anomaly.anom_1"]


def test_context_propagation_avoids_full_ledger_in_strategic_prompt() -> None:
    """Verify Stage 3 receives validated reasoning state, not the full ledger."""

    state = ReasoningState(period_slug="2026_12", evidence_ledger=_ledger())
    state.add_stage_result(
        ReasoningStageResult("financial_performance", "Financial", True, _stage_1(), (), {})
    )
    prompt = build_strategic_synthesis_prompt(
        state=state,
        finance_summary=_finance_summary(),
        period_slug="2026_12",
    )

    assert "validated_reasoning_state" in prompt
    assert "evidence_ledger" not in prompt
    assert "El resultado operativo es positivo" in prompt


def test_duplicate_context_prevention_in_financial_prompt() -> None:
    """Verify Stage 1 prompt does not duplicate evidence package row payloads."""

    prompt = build_financial_performance_prompt(
        evidence_ledger=_ledger(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        period_slug="2026_12",
    )

    assert "payroll_breakdown" not in prompt
    assert prompt.count("finance.metric.net_operating_result") >= 1


def test_independent_stage_validation_rejects_unsupported_number() -> None:
    """Verify Stage 1 validation rejects invented values before later stages."""

    payload = _stage_1()
    payload["claims"][0]["text"] = "El resultado operativo inventado es 9999."
    validation = validate_reasoning_stage_response(
        json.dumps(payload, ensure_ascii=False),
        stage_id="financial_performance",
        evidence_ledger=_ledger(),
    )

    assert not validation.is_valid
    assert any("unsupported number" in error for error in validation.errors)


def test_alias_keys_normalize_correctly() -> None:
    """Verify safe synonymous keys normalize into the minimal schema."""

    payload = {
        "identified_risks": [{"text": "El riesgo requiere control.", "evidence_ids": ["anomaly.anom_1"], "confidence_level": 0.7}],
        "identified_opportunities": [{"text": "La cobranza permite sostener liquidez.", "evidence_ids": ["finance.metric.collection_rate"], "confidence_level": 0.7}],
        "financial_claims": [{"text": "El resultado operativo es positivo.", "evidence_ids": ["finance.metric.net_operating_result"], "confidence_level": 0.8, "claim_type": "fact"}],
        "questions": [],
    }

    normalized, changes = normalize_reasoning_stage_payload(payload)

    assert set(normalized) == {"claims", "risks", "opportunities", "open_questions"}
    assert normalized["claims"][0]["confidence"] == 0.8
    assert any(change["from"] == "identified_risks" for change in changes)


def test_wrapper_object_unwraps_without_inventing_claims() -> None:
    """Verify adapter unwraps one obvious wrapper and preserves item content."""

    wrapped = {"financial_reasoning": {"claims": [], "risks": [], "opportunities": [], "open_questions": []}}
    normalized, changes = normalize_reasoning_stage_payload(wrapped)

    assert normalized == {"claims": [], "risks": [], "opportunities": [], "open_questions": []}
    assert changes == [{"kind": "unwrap", "from": "financial_reasoning", "to": "root"}]


def test_unknown_top_level_keys_rejected_after_normalization() -> None:
    """Verify unknown model keys remain rejected after safe alias normalization."""

    payload = {**_stage_1(), "unexpected": []}
    validation = validate_reasoning_stage_response(
        json.dumps(payload, ensure_ascii=False),
        stage_id="financial_performance",
        evidence_ledger=_ledger(),
    )

    assert not validation.is_valid
    assert validation.errors[0].startswith("schema:")


def test_stage_1_semantic_alias_output_becomes_valid() -> None:
    """Verify observed Ollama-style aliases are accepted after normalization."""

    payload = {
        "financial_claims": [
            {
                "text": "El resultado operativo es positivo según la evidencia actual.",
                "evidence_ids": ["finance.metric.net_operating_result"],
                "confidence_level": 0.8,
                "claim_type": "fact",
            }
        ],
        "identified_risks": [
            {
                "text": "El gasto departamental requiere seguimiento ejecutivo.",
                "evidence_ids": ["anomaly.anom_1"],
                "confidence_level": 0.7,
            }
        ],
        "identified_opportunities": [],
        "questions": [],
    }
    validation = validate_reasoning_stage_response(
        json.dumps(payload, ensure_ascii=False),
        stage_id="financial_performance",
        evidence_ledger=_ledger(),
    )

    assert validation.is_valid
    assert validation.payload is not None
    assert validation.payload["_schema_normalizations"]


def test_schema_only_retry_preserves_original_fact_content() -> None:
    """Verify schema retry can restructure aliases without adding evidence."""

    aliased = {
        "financial_claims": [
            {
                "text": "El resultado operativo es positivo según la evidencia actual.",
                "evidence_ids": ["finance.metric.net_operating_result"],
                "confidence_level": 0.8,
                "claim_type": "fact",
            }
        ],
        "identified_risks": [],
        "identified_opportunities": [],
        "questions": [],
        "confidence_level": 0.8,
    }
    repaired = {
        "claims": aliased["financial_claims"],
        "risks": [],
        "opportunities": [],
        "open_questions": [],
    }
    client = FakeReasoningClient((aliased, repaired, _stage_2(), _stage_3()))
    result = create_modular_strategic_analysis(
        client=client,
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )

    assert result.accepted
    first_stage = result.analysis_document["reasoning_state"]["stage_results"][0]
    assert first_stage["telemetry"]["schema_retry_attempted"] is True
    assert first_stage["payload"]["claims"][0]["evidence_ids"] == ["finance.metric.net_operating_result"]


def test_stage_validation_rejection_is_telemetry_category() -> None:
    """Verify schema-invalid stage output is categorized as validation rejection."""

    client = FakeReasoningClient(({"bad": "shape"}, {"bad": "shape"}))
    result = create_modular_strategic_analysis(
        client=client,
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )

    first_stage = result.analysis_document["reasoning_state"]["stage_results"][0]
    assert first_stage["telemetry"]["error_category"] == "validation_rejection"


def test_modular_pipeline_runs_three_stages_with_mocked_ollama() -> None:
    """Verify the modular pipeline returns accepted Step-9-compatible output."""

    client = FakeReasoningClient((_stage_1(), _stage_2(), _stage_3()))
    result = create_modular_strategic_analysis(
        client=client,
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )

    assert result.accepted
    assert len(client.prompts) == 3
    assert result.analysis_document["analysis_source"] == "ollama_modular_reasoning"
    assert result.analysis_document["reasoning_state"]["reasoning_outputs"]["strategic_synthesis"]


def test_stage_timeout_checkpoint_metadata_is_preserved() -> None:
    """Verify a timed-out modular stage is recorded in ReasoningState."""

    class SlowClient(FakeReasoningClient):
        """Fake client whose call exceeds the configured stage timeout."""

        def generate_with_metadata(self, prompt: str) -> dict[str, Any]:
            """Return valid JSON but with no need for a real sleep."""

            result = super().generate_with_metadata(prompt)
            return result

    result = create_modular_strategic_analysis(
        client=SlowClient((_stage_1(), _stage_2(), _stage_3())),
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
        stage_timeout_seconds=0.0,
    )

    assert not result.accepted
    first_stage = result.analysis_document["reasoning_state"]["stage_results"][0]
    assert first_stage["telemetry"]["error_category"] == "stage_timeout"


def test_report_generation_reads_validated_reasoning_state() -> None:
    """Verify report model can render from ReasoningState strategic synthesis."""

    result = create_modular_strategic_analysis(
        client=FakeReasoningClient((_stage_1(), _stage_2(), _stage_3())),
        evidence_package=_evidence_package(),
        finance_summary=_finance_summary(),
        anomaly_report=_anomaly_report(),
        risk_summary=_risk_summary(),
        period_slug="2026_12",
    )
    document = dict(result.analysis_document)
    document["analysis"] = {}
    model = build_report_model(
        ReportInputBundle(
            period_slug="2026_12",
            finance_summary=_finance_summary(),
            kpi_summary=(),
            anomaly_report=_anomaly_report(),
            evidence_package=_evidence_package(),
            strategic_analysis=document,
            source_files=(
                "outputs/calculations/finance_summary_2026_12.json",
                "outputs/calculations/kpi_summary_2026_12.json",
                "outputs/anomalies/anomaly_report_2026_12.json",
                "outputs/evidence/evidence_package_2026_12.json",
                "outputs/analysis/strategic_analysis_2026_12.json",
            ),
        )
    ).to_dict()

    executive = next(section for section in model["sections"] if section["section_id"] == "executive_summary")
    assert "posición financiera" in executive["content"]["summary"]
